### ISSUE TITLE
Can you do me a favor? Your solution code is publicly available to UW students

### ISSUE THREAD

**Issue by whitakerbrand** [nayuki/Huffman-Coding#1]
This repository contains solution code to one or more of our homework assignments here at University of Washington. It is indexed by Google, which enables students that are currently taking our class to find it and cheat on their assignments. Making your repository private, or simply removing your code from GitHub, would help us out a lot. For me personally, it reduces the amount of academic misconduct research I have to do, but more importantly, it helps to keep our students a little more honest. We understand the temptation, especially when it only takes a student 15 seconds searching on Google. With your help, we can give them enough time to think twice about what they are doing before they taste the sweet forbidden fruit of a pre-completed homework.

As a word of warning to any UW students who have come across this while trying to complete a homework:

I know it's tempting, but you know better than that. Delete any code you found online, take another late day, and go to the IPL tomorrow. You may lose a couple points, but you keep your integrity. You are going to do the right thing; I have faith in you.

If that doesn't convince you...make sure you are informed:

If you get caught, it is highly likely you will lose all the points on the assignment, and may face repercussions from the University.
I know about this solution, and I have programmatic systems that leverage online solutions like these to find misconduct. You think you can get around it by changing comments or variables, or rearranging blocks of code, but you can't. I care about the academic integrity of our program; finding misconduct is my full time job. (Not for other schools. Just UW. Just CSE. Just 142, 143, and 143x). If you are going to cheat, it's pretty much you versus me.

Do your own work.

My name is Whitaker Brand; more information about our courses can be found here: 
http://www.cs.washington.edu/142/ 

Thank you,
Whitaker Brand
Intro Support Staff, Computer Science & Engineering
University of Washington
whitab@cs.washington.edu

**Comment by nayuki** [comment]
Thanks for taking the time to report this issue. I was still a university student a few short years ago and understand the seriousness of plagiarism and academic integrity.

I understand that you already have technical and social systems in place to detect and handle students cheating, but you want to avoid the problem at the source and reduce the need to administer unpleasant punishment sessions.

-----

That being said, I feel that it is better for me to leave this code published online, made publicly available.

Firstly I did not write this code in response to any particular homework assignment (re: your allegation "This repository contains solution code to one or more of our homework assignments here at University of Washington"). This is my implementation of a well-known general CS concept. I first published the code in May 2011, four years before you notified me of a problem.

I wish to keep the code published because it is meant to demonstrate my own skill in implementing and documenting an algorithm. The code shows the way I organize the logic and name the variables/components, as well as the way I deal with formatting and other minutiae.

There are plenty of other Huffman coding implementations available online (as you have acknowledged), which I'm sure are just as easy to steal as mine. There's no way you can get everyone to retract their solution, and to target only myself would be considered unfair.

Finally, I believe that my work is infinitesimally advancing the state of common knowledge. If something becomes so widely understood and trivial to do, what is the value of assigning an exercise to re-discover it? For example students are not expected to derive the quadratic equation from scratch because the solution is readily available in mathematical literature. The same goes for algorithms as for math; the profound discoveries of yesterday will become the trivial textbook solutions of today. I see no reason to hold back the inevitable progress of knowledge.

I respectfully thank you for your time.  
Nayuki Minase - Project Nayuki - http://www.nayuki.io/

**Comment by narlah** [comment]
This code actually helped me while writing my own huffman coder/decoder. On the bit writing/reading part especially. I am not a CS student with an assignment (35 y old here, studied math). So i think the point nayuki makes is pretty valid - this piece of code really helps people that want to expand their knowledge, so id stand behind his decision any day! Keep up the good work mate, and thanks.
